WPI-CS3733-C17-Gamma/project-pather

- src/main/java/ApplicationController.java
- src/main/java/DisplayController.java
- src/main/java/GraphNode.java
- src/main/java/MapAdminController.java
- src/main/java/Room.java
ApplicationController, Room, GraphNode, MapAdminController, and
DisplayController.
> Add new classes

- src/main/java/AStarNode.java
- src/main/java/DatabaseManager.java
- src/main/java/FloorPoint.java
- src/main/java/GraphNetwork.java
GraphNetwork, DatabaseManager, FloorPoint, AStarNode
> Add class stubs

- src/main/java/Directory.java
- src/main/java/Map.java
- src/main/java/MapAdminController.java
- src/test/java/AddRoomToNodeTest.java
- src/test/java/DeleteRoomTest.java
- src/test/java/GetRoomByNodeTest.java
Has a few fixes for master, and some new functions. Might need more in the future for testing.
> Feature select node

- .gitignore
- src/main/java/DatabaseManager.java
- src/main/java/Directory.java
- src/main/java/DirectoryEntry.java
- src/main/java/FloorPoint.java
- src/main/java/GraphNetwork.java
- src/main/java/GraphNode.java
- src/main/java/Map.java
- src/main/java/Room.java
- src/test/java/DatabaseTest.java
A (seemingly) complete implementation of DatabaseManager.load().
'Room's do not have a list of 'DirectoryEntry's, as that was not in the object model.
> Database Loading

- src/main/java/AStarNode.java
- src/main/java/Directory.java
- src/main/java/GraphNetwork.java
- src/main/java/PatientController.java
- src/main/java/Room.java
- src/test/java/DirectoryTest.java
- src/test/java/GetPathTest.java
Probably will encounter some merge conflict in Room.equals and such.
> Implement getPath

- src/main/java/Directory.java
- src/main/java/DirectoryAdminController.java
- src/test/java/DirectoryAdminControllerTest.java
Also adds delete entry and get entry in Directory,
as well as the tester class for DirectoryAdminController
> Implement saveEntry in DirectoryAdminController

- src/main/java/Directory.java
- src/main/java/GraphNetwork.java
Add type to ArrayLists, remove random import
> Fix some compiler warnings

- src/main/java/GraphNetwork.java
- src/main/java/Map.java
- src/test/java/DelectConnectionTest.java
- src/test/java/DeleteConnectionTest.java
Completed deleteConnection on Map, GraphNetwork, and MapAdminController along with DeleteConnectionTests
> Feature delete connection

- src/main/java/DatabaseManager.java
- src/main/java/GraphNetwork.java
- src/main/java/GraphNode.java
- src/main/java/Map.java
- src/test/java/AddConnectionTest.java
Fixed addConnection() and changed the adjacent attributes on nodes to private
> Refactor add connection

- src/main/java/DatabaseManager.java
PreparedStatement makes SQL queries, which fail if the tables
referenced do not exist
> Init database before creating PreparedStatement

- src/main/java/GraphNetwork.java
- src/main/java/PathNotFoundException.java
- src/test/java/GetPathTest.java
PathNotFoundException, GetPathTest, GraphNetwork
Nice Hair by the way!!!
> Add and modify classes

- src/main/java/DatabaseManager.java
- src/test/java/DatabaseTest.java
- increase size of Entries Name field to 40
- Use sorted Map (TreeMap) for retrieval, so as to preserve the
LinkedList's order in save->load tests
- Also get rooms and entries sorted by ID
- Added a test that verifies this behaviour
> Fix errors with DB saving and tests

- src/main/java/DatabaseManager.java
- src/main/java/GraphNode.java
- src/main/java/PatientController.java
- src/test/java/AddConnectionTest.java
- src/test/java/AddRoomToNodeTest.java
- src/test/java/DatabaseTest.java
- src/test/java/DeleteConnectionTest.java
- src/test/java/DeleteNodeTest.java
- src/test/java/DeleteRoomTest.java
- src/test/java/GetPathTest.java
- src/test/java/GetRoomByNodeTest.java
- src/test/java/IDTest.java
- src/test/java/PointSearchTest.java
- creates a FloorPoint internally, which is the desired behaviour in
almost all cases
> Add alternate constructor for GraphNode

- src/main/java/FloorPoint.java
- src/main/java/GraphNetwork.java
- src/test/java/GetPathTest.java
Fix distance function on FloorPoint. Fix GetPathTests
> Modify class

- src/main/java/DatabaseManager.java
Keep track of which nodes have been added to the DB, and only add
edges when their nodes have been added
> Fix DatabaseManager.write constraint violation errors

- src/main/java/ApplicationController.java
- src/main/java/DirectoryAdminController.java
- src/main/java/DisplayController.java
- src/main/java/MapAdminController.java
- src/main/java/PatientController.java
- src/main/resources/AdminDisplay.fxml
Refactored the code in the displays to be decent. The biggest changes are in the map admin controller. The other changes in the application controller are just for ease of use.
> Display refactor

- src/main/java/MapAdminController.java
To add a node, one will double click.
> Added the doubl click feature

- src/main/java/ApplicationController.java
- src/main/java/PatientController.java
- src/main/resources/PatientDisplay.fxml
Patient Display now resizes! yay
> Add resize

- src/main/java/ApplicationController.java
- src/main/java/IProxyImage.java
- src/main/java/ProxyImage.java
- src/main/java/RealImage.java
There is no reflection. This is purely for lazy loading (and I think that is good enough). Wong did say that a junior developer should be able to do this, which seems unreasonable if it involved all of the reflection. This is just using the basic design pattern from Wikipedia to delay loading of images.
> Created proxy pattern to delay image loading

- src/main/java/DatabaseManager.java
- src/main/java/Directory.java
- src/main/java/MapAdminController.java
- src/main/java/PatientController.java
- src/main/java/Room.java
> Allow adding nodes to rooms without a location

- src/main/java/GraphNetwork.java
- src/main/java/Map.java
- src/main/java/PatientController.java
- src/test/java/MultiFloorSubPathTest.java
- src/test/java/TextualDirectionsTest.java
Will also fix the double reversing of the path,
and update the test cases as such.
> Improve textual directions, and its associated methods

- src/main/resources/PatientDisplay.fxml
Fixed Patient Display Initial State
> Fix Patient Display

- src/main/java/ApplicationController.java
- src/main/java/LoginController.java
> Fix centering

- src/main/java/Login.java
- src/main/java/LoginController.java
- src/main/resources/LoginDisplay.fxml
- Login jumps directly to Directory Editor
> Force use of username/password, simplify login process

- src/main/java/PatientController.java
Currently selected map is now highlighted in multiMapDisplay
> Highlight Map

- src/main/java/PatientController.java
- src/main/resources/PatientDisplay.fxml
The initial search state is now consistent with the home screen
> Fix initial search state

- src/main/java/PatientController.java
> Paths show on minimap

- src/main/java/MapAdminController.java
Fix adding nodes when other nodes are selected
> Node selection

- src/main/java/CircularContextMenu.java
- src/main/java/ContextMenuElement.java
- src/main/java/PatientController.java
Fixed a bug.
Added a hide method
Commented stuff
> Comment context menu

- src/main/java/PatientController.java
Entries are given a higher priority if the
first letter of the search is not a number
> Search now gives both rooms and entries

- src/main/java/Directory.java
- src/main/java/Map.java
- src/main/java/PatientController.java
- Will need to be slightly changed later for multiple Kiosks
Resolves #67.
> Allow for the Kiosk location to be queried at runtime

- src/main/java/MapAdminController.java
> Correctly rename Rooms in MapAdminController

- src/main/java/MapAdminController.java
- src/main/resources/MapAdminDisplay.fxml
- Adds all of the tool toggles to a toggleTools toggleGroup
- Each on action points to one function that handles the update
> Simplify MapAdmin significantly by using a toggleGroup

- src/main/java/MapAdminController.java
- also simplify changeState a bit
> Fix nodes being deselected when exiting tools

- src/main/java/app/display/DirectoryAdminController.java
- src/main/resources/DirectoryAdminDisplay.fxml
- remove old unused code, move to VBox and GridPane instead of AnchorPane
> Clean up DirectoryAdminDisplay and Controller

- src/main/java/app/dataPrimitives/Room.java
- src/main/java/app/datastore/Directory.java
- src/main/java/app/datastore/Map.java
- src/main/java/app/display/MapAdminController.java
- src/main/resources/MapAdminDisplay.fxml
Clicking on a room the map admin can set that
location as the default start location.
NOTE the button needs changing (maybe to context menu)
> Added change kiosk feature

- src/main/java/app/applicationControl/ApplicationController.java
- src/main/java/app/display/AdminController.java
- src/main/java/app/display/AdminToolsController.java
- src/main/java/app/display/DirectoryAdminController.java
- src/main/java/app/display/DisplayController.java
- src/main/java/app/display/LoginController.java
- src/main/java/app/display/MapAdminController.java
- src/main/java/app/display/PatientController.java
- src/main/resources/AdminDisplay.fxml
- src/main/resources/AdminTools.fxml
- src/main/resources/DirectoryAdminDisplay.fxml
- src/main/resources/LoginDisplay.fxml
- src/main/resources/MapAdminDisplay.fxml
- src/test/java/app/CreateEntryTest.java
- src/test/java/app/display/DirectoryAdminControllerTest.java
Also includes @iwwoods cleanup.
> Feature tabbed admin

- build.gradle
Added dependency to radial menu in build.gradle. To add the dependency to the project structure in intellij, click refresh in the gradle project manager
> Fixed dependency on radial menu

- src/main/java/app/display/MapAdminController.java
- src/main/resources/MapAdminDisplay.fxml
- Uses ToolBars and GridPanes for layout instead of AnchorPanes
- Elevator menu uses CustomMenuItems and CheckBoxes
- Floor change is a ComboBox
> Clean up MapAdminDisplay

- src/main/java/app/applicationControl/ApplicationController.java
- src/main/java/app/display/LoginController.java
- src/main/resources/LoginDisplay.fxml
- Switch to GridPane, remove useless stuff
> Clean up LoginDisplay

- src/main/java/app/display/DirectoryAdminController.java
- add listeners to selectedItemProperty instead of onclick
- remove unnecessary listener
- use lambdas instead of anonymous classes
> Simplify/Correct ListViews in DirectoryAdminController

- src/main/java/app/display/DisplayController.java
- src/main/java/app/display/MapAdminController.java
You can now drag to select and delete multiple nodes
> Add drag to select

- build.gradle
- src/main/java/app/applicationControl/Login.java
- src/main/resources/DirectoryAdminDisplay.fxml
> login encryption finally working

- src/main/java/app/display/MapAdminController.java
- src/main/resources/MapAdminDisplay.fxml
- src/main/resources/mapAdminDisplay.css
> Disable/re-enable Map Admin buttons when necessary

- src/main/java/app/display/MapAdminController.java
> Changed the node and connections in mapadmin

- src/main/java/app/display/MapAdminController.java
You can now delete highlighted nodes using the delete node button on the mapAdmin UI
> Fix delete Node Bug

- src/main/java/app/applicationControl/ApplicationController.java
- src/main/java/app/display/DisplayController.java
- src/main/java/app/display/LoginController.java
- src/main/java/app/display/PatientController.java
- src/main/resources/LoginDisplay.fxml
- src/main/resources/design.css
Added highlights to buttons.
Change the login window to look more minimalistic
> Refactor patient display

- src/main/java/app/display/PatientController.java
Your dream patient display label
> label change
